# Generated by Django 4.2.7 on 2023-12-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
