# Generated by Django 4.2.7 on 2023-12-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editorial",
            fields=[
                ("ideditorial", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="editoriales/"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
